import type { Metadata } from "next";

import Footer from "@/components/LandingPage/Footer/Footer";
import Navbar from "@/components/LandingPage/NavBar/Navbar";

export const metadata: Metadata = {
  title: "Phase",
  description: "Generated by create next app",
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`w-[80vw] mx-40`}>
      <Navbar />
      {children}
    </div>
  );
}
